// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_IxkOjuzhOHx0cBIlbiuWpgJPi0mdtR0',
    appId: '1:988422204034:android:90fc7d08cb677c5acde29b',
    messagingSenderId: '988422204034',
    projectId: 'plexus-cloud-fcm',
    storageBucket: 'plexus-cloud-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFbxRLb2VNSGEWKXoCJWUElClL_TOZqAU',
    appId: '1:988422204034:ios:b5306bac709beb58cde29b',
    messagingSenderId: '988422204034',
    projectId: 'plexus-cloud-fcm',
    storageBucket: 'plexus-cloud-fcm.firebasestorage.app',
    iosBundleId: 'com.pleuxltd.plexuspules',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCARn9-DQ3joz_xrydGyarT5XTIc97powc',
    appId: '1:988422204034:web:9910ab5d6c0274a9cde29b',
    messagingSenderId: '988422204034',
    projectId: 'plexus-cloud-fcm',
    authDomain: 'plexus-cloud-fcm.firebaseapp.com',
    storageBucket: 'plexus-cloud-fcm.firebasestorage.app',
    measurementId: 'G-F368J00XMT',
  );

}